Repository Nanito111/CAPSTONE_002D, pull requests merged in 2024-10, with the labels that each got.

#120 ADD: Correccion de diagrama de secuencia
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagrama de secuencia/DS_AdministracionDispositivos.drawio
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagrama de secuencia/DS_AdministracionDispositivos_Blanco.png
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagrama de secuencia/DS_Dashboard.drawio
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagrama de secuencia/DS_Dashboard_Blanco.png
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagrama de secuencia/DS_InicioSesion.drawio
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagrama de secuencia/DS_InicioSesion_Blanco.png
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagrama de secuencia/DS_RegistroDispositivo.drawio
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagrama de secuencia/DS_RegistroDispositivo_Blanco.png
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagrama de secuencia/DS_RegistroUsuario.drawio
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagrama de secuencia/DS_RegistroUsuario_Blanco.png
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagrama de secuencia/DiagramaSecuenciaV2.drawio
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagrama de secuencia/DiagramaSecuenciaV2_blanco.drawio.png
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagrama de secuencia/DiagramaSecuenciaV2_negro.drawio.png
Labels: bug, documentation

#121 UPD: nombre y separacion diagramas
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagrama de comunicacion/DiagramaComunicacionInicioSesion.png
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagrama de comunicacion/DiagramaComunicacionRegistrarDispositivo.png
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagrama de comunicacion/DiagramaComunicacionRegistroUsuario.png
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagrama de comunicacion/DiagramaComunicacionVerDashboard.png
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagrama de comunicacion/DiagramaComunicacionVerDispositivo.png
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagrama de comunicacion/DiagramaComunicaciones_blanco.drawio.png
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagrama de comunicacion/DiagramaComunicaciones_negro.drawio.png
Labels: documentation, improvement

#122 FIX: Diagramas casos de uso
  Fase 2/Evidencias Grupales/Diagramas/Vista Escenarios/DiagramaCasoDeUsoDispositivo.png
  Fase 2/Evidencias Grupales/Diagramas/Vista Escenarios/DiagramaCasoDeUsosWeb.png
Labels: documentation, improvement

#123 ADD: Diagrama de clases
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagrama de Clases/Diagrama de Clases.drawio
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagrama de Clases/Diagrama de Clases.jpg
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagrama de Clases/Diagrama de Clases.png
Labels: documentation

#130 ADD:Evidencia base de datos
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/Diccionario de datos BD.xlsx
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/Logical_modeloBD.png
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/Relacional_modeloBD.png
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/modelo_logico_BD_energy_meter.pdf
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/modelo_relacional_BD_energy_meter.pdf
Labels: documentation

#124 ADD:Diagramas de comunicacion arreglados
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagrama de comunicacion/DCAdministracionDispositivos.drawio
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagrama de comunicacion/DCAdministracionDispositivos_blanco.drawio.png
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagrama de comunicacion/DCDashboard.drawio
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagrama de comunicacion/DCDashboard_blanco.drawio.png
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagrama de comunicacion/DCInicioSesion.drawio
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagrama de comunicacion/DCInicioSesion_blanco.drawio.png
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagrama de comunicacion/DCRegistroDispositivo.drawio
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagrama de comunicacion/DCRegistroDispositivo_blanco.drawio.png
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagrama de comunicacion/DCRegistroUsuario.drawio
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagrama de comunicacion/DCRegistroUsuario_blanco.drawio.png
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagrama de comunicacion/DiagramaComunicacionInicioSesion.png
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagrama de comunicacion/DiagramaComunicacionRegistrarDispositivo.png
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagrama de comunicacion/DiagramaComunicacionRegistroUsuario.png
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagrama de comunicacion/DiagramaComunicacionVerDashboard.png
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagrama de comunicacion/DiagramaComunicacionVerDispositivo.png
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagrama de comunicacion/DiagramaComunicacionesV2.0.drawio
  Fase 2/Evidencias Grupales/Diagramas/Vista Procesos/DAActualizarContraseña.drawio
  Fase 2/Evidencias Grupales/Diagramas/Vista Procesos/DAActualizarContraseña_blanco.drawio.png
  Fase 2/Evidencias Grupales/Diagramas/Vista Procesos/DAAgregar dispositivo_blanco.drawio.png
  Fase 2/Evidencias Grupales/Diagramas/Vista Procesos/DAAgregarDispositivo.drawio
  Fase 2/Evidencias Grupales/Diagramas/Vista Procesos/DARegistrarUsuario.drawio
  Fase 2/Evidencias Grupales/Diagramas/Vista Procesos/DARegistrarUsuario_blanco.drawio.png
  Fase 2/Evidencias Grupales/Diagramas/Vista Procesos/DAVisualizarDashboard.drawio
  Fase 2/Evidencias Grupales/Diagramas/Vista Procesos/DAVisualizarDashboard_blanco.drawio.png
Labels: bug, documentation

#132 Cambiar nombre user a diagramas
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/Diccionario de datos BD.xlsx
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/Logical_modeloBD.png
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/Modelo_Logico_DB.png
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/Modelo_Relacional_DB.png
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/Relacional_modeloBD.png
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/modelo_logico_BD_energy_meter.pdf
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/modelo_relacional_BD_energy_meter.pdf
Labels: bug

#133 131 cambiar nombre a tabla user scripts
  database/create_tables_database.ddl
  database/drop_tables_database.ddl
Labels: bug

#137 Database
  database/create_tables_database.ddl
  database/drop_tables_database.ddl
Labels: feature

#141 ADD:Evidencia individual Jorge Parra (yo)
  Fase 2/Evidencias Individuales/Parra_Jorge_2.1_APT122_DiarioReflexionFase2.docx
Labels: documentation

#145 UPD: Mover Scripts ddl
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/create_tables_database.ddl
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/drop_tables_database.ddl
Labels: improvement

#146 ADD: Diario de reflexion fase 2
  Fase 2/Evidencias Individuales/Galdames_Francisco_2.1_APT122_DiarioReflexionFase2.docx
Labels: improvement

#148 UPD: Subir doc 2.4
  Fase 2/Evidencias Grupales/2.4_GuiaEstudiante_Fase 2_DesarrolloProyecto APT.docx
  Fase 2/Evidencias Grupales/Diagramas/Vista Despliegue/DiagramaComponentes.drawio
  Fase 2/Evidencias Grupales/Diagramas/Vista Despliegue/DiagramaComponentes.png
  Fase 2/Evidencias Grupales/Diagramas/Vista Despliegue/DiagramaPaquetes.drawio
  Fase 2/Evidencias Grupales/Diagramas/Vista Despliegue/DiagramaPaquetes.png
  Fase 2/Evidencias Grupales/Diagramas/Vista Escenarios/DiagramaCasoDeUsoDispositivo.png
  Fase 2/Evidencias Grupales/Diagramas/Vista Escenarios/DiagramaCasoDeUsosWeb.png
  Fase 2/Evidencias Grupales/Diagramas/Vista Escenarios/DiagramasCasosDeUso.drawio
  Fase 2/Evidencias Grupales/Diagramas/Vista Fisica/Diagrama despliegue.drawio
  Fase 2/Evidencias Grupales/Diagramas/Vista Fisica/Diagrama despliegue.png
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagrama de Clases/Diagrama de Clases.drawio
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagrama de Clases/Diagrama de Clases.jpg
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagrama de Clases/Diagrama de Clases.png
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagrama de comunicacion/DCAdministracionDispositivos.drawio
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagrama de comunicacion/DCAdministracionDispositivos_blanco.drawio.png
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagrama de comunicacion/DCDashboard.drawio
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagrama de comunicacion/DCDashboard_blanco.drawio.png
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagrama de comunicacion/DCInicioSesion.drawio
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagrama de comunicacion/DCInicioSesion_blanco.drawio.png
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagrama de comunicacion/DCRegistroDispositivo.drawio
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagrama de comunicacion/DCRegistroDispositivo_blanco.drawio.png
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagrama de comunicacion/DCRegistroUsuario.drawio
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagrama de comunicacion/DCRegistroUsuario_blanco.drawio.png
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagrama de secuencia/DS_AdministracionDispositivos.drawio
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagrama de secuencia/DS_AdministracionDispositivos_Blanco.png
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagrama de secuencia/DS_Dashboard.drawio
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagrama de secuencia/DS_Dashboard_Blanco.png
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagrama de secuencia/DS_InicioSesion.drawio
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagrama de secuencia/DS_InicioSesion_Blanco.png
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagrama de secuencia/DS_RegistroDispositivo.drawio
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagrama de secuencia/DS_RegistroDispositivo_Blanco.png
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagrama de secuencia/DS_RegistroUsuario.drawio
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagrama de secuencia/DS_RegistroUsuario_Blanco.png
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagramas de flujo/DiagramaFlujoAdministracionDispositivos.png
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagramas de flujo/DiagramaFlujoAgregarDispositivo.png
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagramas de flujo/DiagramaFlujoAutenticacion.png
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagramas de flujo/DiagramaFlujoConfigCuenta.png
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagramas de flujo/DiagramaFlujoConfigNotificaciones.png
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagramas de flujo/DiagramaFlujoDashboard.png
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagramas de flujo/DiagramasFlujo.drawio
  Fase 2/Evidencias Grupales/Diagramas/Vista Procesos/DAActualizarContraseña.drawio
  Fase 2/Evidencias Grupales/Diagramas/Vista Procesos/DAActualizarContraseña_blanco.drawio.png
  Fase 2/Evidencias Grupales/Diagramas/Vista Procesos/DAAgregar dispositivo_blanco.drawio.png
  Fase 2/Evidencias Grupales/Diagramas/Vista Procesos/DAAgregarDispositivo.drawio
  Fase 2/Evidencias Grupales/Diagramas/Vista Procesos/DARegistrarUsuario.drawio
  Fase 2/Evidencias Grupales/Diagramas/Vista Procesos/DARegistrarUsuario_blanco.drawio.png
  Fase 2/Evidencias Grupales/Diagramas/Vista Procesos/DAVisualizarDashboard.drawio
  Fase 2/Evidencias Grupales/Diagramas/Vista Procesos/DAVisualizarDashboard_blanco.drawio.png
Labels: documentation

#150 ADD: Vistas aplicacion
  Fase 2/Evidencias Proyecto/Evidencias de documentación/Vistas Aplicacion/LEERME.TXT
  Fase 2/Evidencias Proyecto/Evidencias de documentación/Vistas Aplicacion/VistaConfiguracionCuenta.png
  Fase 2/Evidencias Proyecto/Evidencias de documentación/Vistas Aplicacion/VistaConfiguracionNotificaciones.png
  Fase 2/Evidencias Proyecto/Evidencias de documentación/Vistas Aplicacion/VistaDashboard.png
  Fase 2/Evidencias Proyecto/Evidencias de documentación/Vistas Aplicacion/VistaDispositivoID.png
  Fase 2/Evidencias Proyecto/Evidencias de documentación/Vistas Aplicacion/VistaDispositivos.png
  Fase 2/Evidencias Proyecto/Evidencias de documentación/Vistas Aplicacion/VistaLogin.png
  Fase 2/Evidencias Proyecto/Evidencias de documentación/Vistas Aplicacion/VistaRegister.png
  Fase 2/Evidencias Proyecto/Evidencias de documentación/Vistas Aplicacion/VistaResponsive.png
  Fase 2/Evidencias Proyecto/Evidencias de documentación/Vistas Aplicacion/VistaSidebarColapsado.png
  Fase 2/Evidencias Proyecto/Evidencias de documentación/Vistas Aplicacion/VistaSidebarExtendido.png
  Fase 2/Evidencias Proyecto/Evidencias de documentación/Vistas Aplicacion/VistaTemaOscuro.png
Labels: documentation

#152 UPD: modificacion carta gantt
  Fase 2/Evidencias Grupales/2.4_GuiaEstudiante_Fase 2_DesarrolloProyecto APT.docx
Labels: documentation

#156 ADD:Cambiar columnas y tablas BD
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/Diccionario de datos BD.xlsx
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/Modelo_Logico_DB.png
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/Modelo_Relacional_DB.png
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/create_tables_database.ddl
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/drop_tables_database.ddl
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/modelo_logico_BD_energy_meter.pdf
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/modelo_relacional_BD_energy_meter.pdf
  database/create_tables_database.ddl
  database/drop_tables_database.ddl
Labels: improvement

#162 ADD:Corregir error de columna contract
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/Diccionario de datos BD.xlsx
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/Modelo_Logico_DB.png
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/Modelo_Relacional_DB.png
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/modelo_logico_BD_energy_meter.pdf
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/modelo_relacional_BD_energy_meter.pdf
  database/create_tables_database.ddl
  database/drop_tables_database.ddl
Labels: bug

#165 Autenticacion y Registro
  backend/pyproject.toml
  backend/requirements
  backend/src/account/exceptions.py
  backend/src/account/router.py
  backend/src/account/schemas.py
  backend/src/constants.py
  backend/src/dependencies.py
  backend/src/login/router.py
  backend/src/login/schemas.py
  backend/src/main.py
  backend/src/models.py
  backend/src/utils/router.py
  backend/src/utils/schemas.py
Labels: feature

#168 Especificar los outputs en endpoints utils
  backend/src/utils/router.py
Labels: improvement
