Repository Nanito111/CAPSTONE_002D, pull requests merged in 2024-12, with the labels that each got.

#257 Endpoint para consultar si dispositivo esta registrado
  backend/src/utils/router.py
Labels: feature

#260 Database
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/Diccionario de datos BD.xlsx
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/Modelo_Logico_DB.png
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/Modelo_Relacional_DB.png
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/modelo_logico_BD_energy_meter.pdf
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/modelo_relacional_BD_energy_meter.pdf
  database/Ingresando_compañia_electrica_devicemodel_y_country.ddl
  database/create_tables_database.ddl
  database/drop_tables_database.ddl
Labels: improvement

#259 Website
  frontend/src/components/auth/LoginForm.tsx
  frontend/src/components/auth/RegisterForm.tsx
  frontend/src/components/charts/CardConsumoActual.tsx
  frontend/src/components/charts/GraficoAreaGradiente.tsx
  frontend/src/components/charts/GraficoBarrasApiladas.tsx
  frontend/src/components/charts/GraficoConsumoDia.tsx
  frontend/src/components/charts/GraficoPie.tsx
  frontend/src/components/charts/MedidorGauge.tsx
  frontend/src/components/placeholders/placeholder-cambiar-contrasena.tsx
  frontend/src/components/placeholders/placeholder-dashboard.tsx
Labels: feature, improvement
