Repository Nanito111/CAPSTONE_002D, pull requests merged in 2024-09, with the labels that each got.

#31 UPD: Añadir archivos sw a .gitignore
  .gitignore
Labels: improvement

#34 30 crear homepage
  frontend/.env.local.example
  frontend/components.json
  frontend/package-lock.json
  frontend/package.json
  frontend/public/sw.js
  frontend/public/workbox-f1770938.js
  frontend/src/app/(home)/account/page.tsx
  frontend/src/app/(home)/categories/page.tsx
  frontend/src/app/(home)/dashboard/page.tsx
  frontend/src/app/(home)/layout.tsx
  frontend/src/app/(home)/posts/new/page.tsx
  frontend/src/app/(home)/posts/page.tsx
  frontend/src/app/(home)/tags/page.tsx
  frontend/src/app/(home)/users/page.tsx
  frontend/src/app/globals.css
  frontend/src/app/icon.ico
  frontend/src/app/layout.tsx
  frontend/src/app/page.tsx
  frontend/src/components/admin-panel/admin-panel-layout.tsx
  frontend/src/components/admin-panel/collapse-menu-button.tsx
  frontend/src/components/admin-panel/content-layout.tsx
  frontend/src/components/admin-panel/footer.tsx
  frontend/src/components/admin-panel/menu.tsx
  frontend/src/components/admin-panel/navbar.tsx
  frontend/src/components/admin-panel/sheet-menu.tsx
  frontend/src/components/admin-panel/sidebar-toggle.tsx
  frontend/src/components/admin-panel/sidebar.tsx
  frontend/src/components/admin-panel/user-nav.tsx
  frontend/src/components/charts/CardConsumoActual.tsx
  frontend/src/components/charts/GraficoAreaGradiente.tsx
  frontend/src/components/charts/GraficoBarrasApiladas.tsx
  frontend/src/components/charts/GraficoConsumoDia.tsx
  frontend/src/components/charts/GraficoPie.tsx
  frontend/src/components/charts/MedidorGauge.tsx
  frontend/src/components/demo/placeholder-dashboard.tsx
  frontend/src/components/dev/TestButton.tsx
  frontend/src/components/mode-toggle.tsx
  frontend/src/components/ui/avatar.tsx
  frontend/src/components/ui/breadcrumb.tsx
  frontend/src/components/ui/card copy.tsx
  frontend/src/components/ui/chart.tsx
  frontend/src/components/ui/collapsible.tsx
  frontend/src/components/ui/dropdown-menu.tsx
  frontend/src/components/ui/scroll-area.tsx
  frontend/src/components/ui/sheet.tsx
  frontend/src/components/ui/tooltip.tsx
  frontend/src/hooks/use-sidebar-toggle.ts
  frontend/src/hooks/use-store.ts
  frontend/src/lib/menu-list.ts
  frontend/src/providers/theme-provider.tsx
Labels: feature

#43 UPD: Cambiar breakpoints en componente
  frontend/src/components/charts/GraficoConsumoDia.tsx
  frontend/src/components/demo/placeholder-dashboard.tsx
Labels: bug

#44 UPD: Añadir botones para volver a pagina principal
  frontend/src/app/login/page.tsx
  frontend/src/app/register/page.tsx
  frontend/src/components/LoginForm.tsx
  frontend/src/components/RegisterForm.tsx
  frontend/src/components/admin-panel/user-nav.tsx
Labels: feature

#52 UPD: Cambiar .gitignore y cambios en sidebar
  .gitignore
  frontend/src/lib/menu-list.ts
Labels: improvement

#56 50 crear pagina notificaciones
  frontend/package-lock.json
  frontend/package.json
  frontend/public/sw.js
  frontend/src/app/(auth)/login/page.tsx
  frontend/src/app/(auth)/register/page.tsx
  frontend/src/app/(home)/account/page.tsx
  frontend/src/app/(home)/categories/page.tsx
  frontend/src/app/(home)/dashboard/page.tsx
  frontend/src/app/(home)/notificaciones/page.tsx
  frontend/src/app/(home)/posts/new/page.tsx
  frontend/src/app/(home)/posts/page.tsx
  frontend/src/app/(home)/tags/page.tsx
  frontend/src/app/(home)/users/page.tsx
  frontend/src/components/auth/LoginForm.tsx
  frontend/src/components/auth/RegisterForm.tsx
  frontend/src/components/config-notificaciones.tsx
  frontend/src/components/placeholders/placeholder-dashboard.tsx
  frontend/src/components/placeholders/placeholder-notificaciones.tsx
  frontend/src/components/ui/checkbox.tsx
  frontend/src/components/ui/form.tsx
  frontend/src/components/ui/toast.tsx
  frontend/src/components/ui/toaster.tsx
  frontend/src/hooks/use-toast.ts
  frontend/src/lib/menu-list.ts
Labels: feature, improvement

#58 Crear action para hacer deploy de api
  .github/workflows/deploy-api.yml
Labels: feature

#60 FIX: bad keyword naming
  .github/workflows/deploy-api.yml
Labels: bug

#63 Mejorar workflow de deploy api
  .github/workflows/deploy-api.yml
  backend/start-api.sh
  backend/stop-api.sh
Labels: improvement

#64 FIX: comando incorrecto para iniciar session tmux
  backend/start-api.sh
Labels: bug

#65 FIX: comandos git faltantes
  .github/workflows/deploy-api.yml
  backend/start-api.sh
Labels: bug

#66 Diversas mejoras en scripts bash de api
  backend/start-api.sh
  backend/stop-api.sh
Labels: bug, improvement

#79 Subir cambios de 'backend' a 'production'
  .github/workflows/deploy-api.yml
  backend/.gitignore
  backend/requirements
  backend/src/config.py
  backend/src/constants.py
  backend/src/database.py
  backend/src/dependencies.py
  backend/src/exceptions.py
  backend/src/health_check/router.py
  backend/src/health_check/utils.py
  backend/src/login/router.py
  backend/src/login/schemas.py
  backend/src/main.py
  backend/src/models.py
  backend/src/pyproject.toml
  backend/start-api.sh
  backend/stop-api.sh
Labels: feature

#83 FIX:Renombrar archivos Fase 1
  Fase 1/Evidencias Grupales/1.5_GuiaEstudiante_Fase 1_Definicion Proyecto APT  (Español).docx
  Fase 1/Evidencias Grupales/Presentación idea proyecto.pptx
Labels: bug, documentation

#87 ADD:Vista Despliegue/Diagrama componentes
  Fase 2/Evidencias Grupales/Diagramas/Vista Despliegue/DiagramaComponentes.drawio
  Fase 2/Evidencias Grupales/Diagramas/Vista Despliegue/DiagramaComponentes.png
Labels: documentation

#88 62 crear archivo verceljson para restringir los deployments
  frontend/vercel.json
Labels: improvement

#90 FIX: Arreglar formulario config cuenta
  frontend/src/components/form-cuenta.tsx
Labels: bug, improvement

#91 ADD: Añadir input de valor kwh en form-cuenta.tsx
  frontend/src/components/form-cuenta.tsx
Labels: improvement

#93 ADD: Vista escenarios
  Fase 2/Evidencias Grupales/Diagramas/Vista Escenarios/DiagramaCasoDeUsoDispositivo.png
  Fase 2/Evidencias Grupales/Diagramas/Vista Escenarios/DiagramaCasoDeUsosWeb.png
  Fase 2/Evidencias Grupales/Diagramas/Vista Escenarios/DiagramasCasosDeUso.drawio
Labels: documentation

#95 ADD: Diagramas de flujo
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagramas de flujo/DiagramaFlujoAdministracionDispositivos.png
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagramas de flujo/DiagramaFlujoAgregarDispositivo.png
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagramas de flujo/DiagramaFlujoAutenticacion.png
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagramas de flujo/DiagramaFlujoConfigCuenta.png
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagramas de flujo/DiagramaFlujoConfigNotificaciones.png
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagramas de flujo/DiagramaFlujoDashboard.png
  Fase 2/Evidencias Grupales/Diagramas/Vista Logica/Diagramas de flujo/DiagramasFlujo.drawio
Labels: documentation
