Repository Nanito111/CAPSTONE_002D, pull requests merged in 2024-11, with the labels that each got.

#169 UPD: crear y subir dotenv en deploy
  .github/workflows/deploy-api.yml
Labels: improvement

#174 ADD: endpoint para consultar info de usuario
  backend/src/account/router.py
  backend/src/account/schemas.py
  backend/src/health_check/router.py
  backend/src/utils/router.py
Labels: improvement

#172 ADD:Guardar cambios hechos en tablas relacionadas a direccion
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/Diccionario de datos BD.xlsx
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/Modelo_Logico_DB.png
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/Modelo_Relacional_DB.png
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/modelo_logico_BD_energy_meter.pdf
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/modelo_relacional_BD_energy_meter.pdf
  database/Ingresando_compañia_electrica_y_country.ddl
  database/create_tables_database.ddl
  database/insertar_comunas.ddl
  database/insertar_regiones.ddl
Labels: improvement

#175 ADD: endpoint para eliminar usuario
  backend/src/account/exceptions.py
  backend/src/account/router.py
Labels: improvement

#176 Diseñar flujo de simulacion
  simulation/assets/devices/computador.glb
  simulation/assets/devices/computador.glb.import
  simulation/assets/devices/hervidor.glb
  simulation/assets/devices/hervidor.glb.import
  simulation/assets/devices/impresora.glb
  simulation/assets/devices/impresora.glb.import
  simulation/assets/devices/laptop.glb
  simulation/assets/devices/laptop.glb.import
  simulation/assets/devices/lavadora.glb
  simulation/assets/devices/lavadora.glb.import
  simulation/assets/devices/microondas.glb
  simulation/assets/devices/microondas.glb.import
  simulation/assets/devices/monitor.glb
  simulation/assets/devices/monitor.glb.import
  simulation/assets/devices/plancha.glb
  simulation/assets/devices/plancha.glb.import
  simulation/assets/devices/refrigerador.glb
  simulation/assets/devices/refrigerador.glb.import
  simulation/assets/devices/secador de pelo.glb
  simulation/assets/devices/secador de pelo.glb.import
  simulation/assets/devices/secadora.glb
  simulation/assets/devices/secadora.glb.import
  simulation/assets/devices/tablet.glb
  simulation/assets/devices/tablet.glb.import
  simulation/assets/devices/televisor.glb
  simulation/assets/devices/televisor.glb.import
  simulation/assets/materials/electric_device_mat.tres
  simulation/assets/materials/objects_mat.tres
  simulation/assets/materials/user_mat.tres
  simulation/assets/objects/escritorio_mesa.glb
  simulation/assets/objects/escritorio_mesa.glb.import
  simulation/assets/objects/silla_simple.glb
  simulation/assets/objects/silla_simple.glb.import
  simulation/assets/objects/silla_simple_brazos.glb
  simulation/assets/objects/silla_simple_brazos.glb.import
  simulation/assets/room.tscn
  simulation/assets/user.tscn
  simulation/docs/flujos e ideas simulacion.excalidraw
  simulation/docs/flujos e ideas simulacion.png
  simulation/docs/flujos e ideas simulacion.png.import
  simulation/project.godot
  simulation/scenes/main.tscn
Labels: feature

#177 ADD:Cambio de columna middle name tabla appuser
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/Diccionario de datos BD.xlsx
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/Modelo_Logico_DB.png
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/Modelo_Relacional_DB.png
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/modelo_logico_BD_energy_meter.pdf
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/modelo_relacional_BD_energy_meter.pdf
  database/create_tables_database.ddl
Labels: improvement

#178 Remover campo middle_name
  backend/src/account/router.py
  backend/src/account/schemas.py
  backend/src/models.py
Labels: improvement

#180 Modificacion de campos de costo en contract para aceptar 0
  backend/src/account/schemas.py
Labels: improvement

#182 Cambiar status code en useralreadyexist
  backend/src/account/exceptions.py
Labels: improvement

#191 ADD: Habilitar cerrar sesion
  frontend/src/app/api/account/killsession/route.ts
  frontend/src/components/admin-panel/menu.tsx
  frontend/src/components/admin-panel/user-nav.tsx
Labels: feature

#193 Endpoint para modificar usuario
  backend/src/account/exceptions.py
  backend/src/account/router.py
  backend/src/account/schemas.py
Labels: feature

#196 Endpoint para cambiar contraseña
  backend/src/account/exceptions.py
  backend/src/account/router.py
  backend/src/account/schemas.py
Labels: feature

#200 186 implementar modificacion datos usuario en cuenta
  frontend/public/email_logo.png
  frontend/src/components/auth/LoginForm.tsx
  frontend/src/components/form-cuenta.tsx
  frontend/src/components/form-editar-cuenta.tsx
  frontend/src/components/placeholders/placeholder-cuenta.tsx
Labels: feature, improvement

#198 UPD: Actualizar pagina bienvenida
  frontend/src/app/page.tsx
  frontend/src/components/more-info-dialog.tsx
Labels: feature, improvement

#204 ADD:Agregar tabla passwordrecoverrequest
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/Diccionario de datos BD.xlsx
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/Modelo_Logico_DB.png
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/Modelo_Relacional_DB.png
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/modelo_logico_BD_energy_meter.pdf
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/modelo_relacional_BD_energy_meter.pdf
  database/create_tables_database.ddl
  database/drop_tables_database.ddl
Labels: improvement

#206 Agregar letras con acentos en validacion nombre
  backend/src/account/schemas.py
Labels: bug

#205 Endpoint para recuperar contraseña
  .github/workflows/deploy-api.yml
  backend/src/account/exceptions.py
  backend/src/account/router.py
  backend/src/account/schemas.py
  backend/src/assets/emails/recover_password.html
  backend/src/constants.py
  backend/src/models.py
Labels: feature

#208 Url de recuperacion contraseña incorrecta en dev
  backend/src/account/router.py
Labels: bug

#210 Endpoint para confirmar recuperacion de contraseña
  backend/src/account/exceptions.py
  backend/src/account/router.py
Labels: feature

#211 201 crear pagina recuperacion contrasea
  frontend/src/app/(auth)/forgot-password/page.tsx
  frontend/src/app/(auth)/recover/[token].tsx
  frontend/src/app/(auth)/recover/[token]/page.tsx
  frontend/src/app/api/account/forgot-password/route.ts
  frontend/src/app/api/utils/confirmar-recover-password/route.ts
  frontend/src/app/api/utils/recover-password/route.ts
  frontend/src/components/auth/ForgotPasswordForm.tsx
  frontend/src/components/auth/LoginForm.tsx
  frontend/src/components/auth/RecoverPasswordForm.tsx
  frontend/src/components/charts/GraficoConsumoActualID.tsx
  frontend/src/components/placeholders/placeholder-dispositivo-id.tsx
Labels: feature, improvement

#212 202 crear pagina modificar contrasea
  frontend/src/app/(home)/cuenta/cambiar-contrasena/page.tsx
  frontend/src/app/api/account/change-password/route.ts
  frontend/src/components/form-editar-cuenta.tsx
  frontend/src/components/more-info-dialog.tsx
  frontend/src/components/placeholders/placeholder-cambiar-contrasena.tsx
Labels: feature, improvement

#214 UPD: Cambiar texto graficos
  frontend/src/components/charts/GraficoAreaGradiente.tsx
  frontend/src/components/charts/GraficoBarrasApiladas.tsx
Labels: improvement

#217 Database
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/Diccionario de datos BD.xlsx
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/Modelo_Logico_DB.png
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/Modelo_Relacional_DB.png
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/create_tables_database.ddl
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/drop_tables_database.ddl
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/modelo_logico_BD_energy_meter.pdf
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/modelo_relacional_BD_energy_meter.pdf
  database/Ingresando_compañia_electrica_y_country.ddl
  database/create_tables_database.ddl
  database/drop_tables_database.ddl
  database/insertar_comunas.ddl
  database/insertar_regiones.ddl
Labels: feature, improvement

#216 Backend
  .github/workflows/deploy-api.yml
  backend/src/account/exceptions.py
  backend/src/account/router.py
  backend/src/account/schemas.py
  backend/src/assets/emails/recover_password.html
  backend/src/constants.py
  backend/src/models.py
Labels: feature, improvement

#226 ADD: evidencias API
  Fase 2/Evidencias Proyecto/Evidencias de sistema/API/.gitignore
  Fase 2/Evidencias Proyecto/Evidencias de sistema/API/requirements
  Fase 2/Evidencias Proyecto/Evidencias de sistema/API/src/account/exceptions.py
  Fase 2/Evidencias Proyecto/Evidencias de sistema/API/src/account/router.py
  Fase 2/Evidencias Proyecto/Evidencias de sistema/API/src/account/schemas.py
  Fase 2/Evidencias Proyecto/Evidencias de sistema/API/src/assets/emails/recover_password.html
  Fase 2/Evidencias Proyecto/Evidencias de sistema/API/src/config.py
  Fase 2/Evidencias Proyecto/Evidencias de sistema/API/src/constants.py
  Fase 2/Evidencias Proyecto/Evidencias de sistema/API/src/database.py
  Fase 2/Evidencias Proyecto/Evidencias de sistema/API/src/dependencies.py
  Fase 2/Evidencias Proyecto/Evidencias de sistema/API/src/exceptions.py
  Fase 2/Evidencias Proyecto/Evidencias de sistema/API/src/health_check/router.py
  Fase 2/Evidencias Proyecto/Evidencias de sistema/API/src/health_check/utils.py
  Fase 2/Evidencias Proyecto/Evidencias de sistema/API/src/login/router.py
  Fase 2/Evidencias Proyecto/Evidencias de sistema/API/src/login/schemas.py
  Fase 2/Evidencias Proyecto/Evidencias de sistema/API/src/main.py
  Fase 2/Evidencias Proyecto/Evidencias de sistema/API/src/models.py
  Fase 2/Evidencias Proyecto/Evidencias de sistema/API/src/pyproject.toml
  Fase 2/Evidencias Proyecto/Evidencias de sistema/API/start-api.sh
  Fase 2/Evidencias Proyecto/Evidencias de sistema/API/stop-api.sh
Labels: documentation, feature

#229 UPD: Fix formularios
  frontend/src/components/auth/RegisterForm.tsx
Labels: bug

#237 Endpoint para agregar dispositivo
  backend/src/account/exceptions.py
  backend/src/account/router.py
  backend/src/account/schemas.py
  backend/src/dependencies.py
  backend/src/devices/exceptions.py
  backend/src/devices/router.py
  backend/src/devices/schemas.py
  backend/src/main.py
  backend/src/models.py
  backend/src/utils/router.py
  backend/src/utils/schemas.py
Labels: feature

#240 Endpoint modificar dispositivo
  backend/src/dependencies.py
  backend/src/devices/exceptions.py
  backend/src/devices/router.py
  backend/src/devices/schemas.py
  backend/src/utils/router.py
Labels: feature

#241 UPD: Randomizar datos
  frontend/src/components/charts/CardConsumoActual.tsx
  frontend/src/components/charts/GraficoAreaGradiente.tsx
  frontend/src/components/charts/GraficoBarrasApiladas.tsx
  frontend/src/components/charts/GraficoConsumoDia.tsx
  frontend/src/components/charts/GraficoPie.tsx
  frontend/src/components/charts/MedidorGauge.tsx
  frontend/src/components/placeholders/placeholder-dashboard.tsx
Labels: improvement

#242 Endpoint para obtener todos los dispositivos del usuario
  backend/src/devices/exceptions.py
  backend/src/devices/router.py
  backend/src/devices/schemas.py
Labels: feature

#235 ADD:Cambios bd noviembre
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/Diccionario de datos BD.xlsx
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/Modelo_Logico_DB.png
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/Modelo_Relacional_DB.png
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/modelo_logico_BD_energy_meter.pdf
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/modelo_relacional_BD_energy_meter.pdf
  database/Ingresando_compañia_electrica_devicemodel_y_country.ddl
  database/create_tables_database.ddl
  database/drop_tables_database.ddl
Labels: improvement

#243 Cambios de bd en backend para dispositivos
  backend/src/devices/router.py
  backend/src/devices/schemas.py
  backend/src/models.py
Labels: improvement

#245 230 feedback error register
  frontend/src/components/auth/RegisterForm.tsx
Labels: improvement

#247 ADD:Cambio de tablas result y datetime a timestamp
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/Diccionario de datos BD.xlsx
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/Modelo_Logico_DB.png
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/Modelo_Relacional_DB.png
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/modelo_logico_BD_energy_meter.pdf
  Fase 2/Evidencias Proyecto/Evidencias de sistema/Base de datos/modelo_relacional_BD_energy_meter.pdf
  database/create_tables_database.ddl
Labels: improvement

#248 Endpoint consumo historico de un dispositivo
  backend/requirements
  backend/src/account/router.py
  backend/src/devices/exceptions.py
  backend/src/devices/router.py
  backend/src/devices/schemas.py
  backend/src/models.py
Labels: feature

#250 Reemplazar StrEnum por Enum con str
  backend/src/devices/schemas.py
Labels: bug

#255 Endpoint para obtener datos historicos de consumo de los dispositivos
  backend/src/devices/router.py
Labels: feature
